appId: uk.gleissner.c64commander
env:
  TIMEOUT: ${TIMEOUT || "15000"}
tags:
  - subflow
---
- runFlow: launch-and-wait.yaml
- retry:
    maxRetries: 3
    commands:
      - runFlow:
          when:
            visible: "Continue in Demo Mode"
          file: continue-demo.yaml
      - tapOn:
          text: "Continue in Demo Mode"
          optional: true
      - waitForAnimationToEnd
      - extendedWaitUntil:
          visible:
            text: "Settings"
          timeout: ${TIMEOUT}
- tapOn:
    id: "tab-settings"
- extendedWaitUntil:
    visible: "Settings"
    timeout: ${TIMEOUT}
- assertVisible: "Settings"
